---
- hosts: db
- name: database assignment
  import_playbook: ../static-assignments/database.yml

- hosts: nginx
- name: nginx assignment
  import_playbook: ../static-assignments/nginx.yml

# - hosts: artifactory
# - name: artifactory assignment
#   import_playbook: ../static-assignments/artifactory.yml

# - hosts: sonar
# - name: sonar assignment
#   ansible.builtin.import_playbook: ../static-assignments/sonar.yml

# - hosts: todo
# - name: Deploy the todo application
#   ansible.builtin.import_playbook: ../static-assignments/deployment.yml

##



# - hosts: all
# - name: Include dynamic variables 
#   import_playbook: ../static-assignments/common.yml 
#   include: ../dynamic-assignments/env-vars.yml
#   tags:
#     - always

# - hosts: uat-webservers
# - name: Webserver assignment
#   import_playbook: ../static-assignments/uat-webservers.yml
  
# - name: Loadbalancers assignment
# - hosts: lb
#   import_playbook: ../static-assignments/loadbalancers.yml
#   when: load_balancer_is_required 


#- name: Include dynamic variables
#  gather_facts: no # due to python interpreter /usr/bin/python absent
#  hosts: all

#- name: import the common playbook
#  import_playbook: ../static-assignments/common.yml
#  tags:
#    - run

#- name: include the env-vars playbook
#  import_playbook: ../dynamic-assignments/env-vars.yml
#  tags:
#    - skip